//#pragma src
//=========================================================
// src/EFM8BB31F32I-C-QFP32_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// Button logic
// short press - fix/release values
// long press (5sec) - calibration. It will cycle from 0EC til 5EC. Release button when desired calibration is found. 
//  Then insert the probe into calibration liquid and wait until it will say, "OK".

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include "main.h"
#include "InitDevice.h"
#include "gen.h"
#include "i2c.h"
#include "SSD1306.h"
#include "button.h"
#include "pgm.h"
#include "bitmaps.h"

volatile glob_t glob;
volatile eeprom_t xdata eeprom_data[1];

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {
  // Call hardware initialization routine

  enter_DefaultMode_from_RESET();

  buttonstate = BUT_NOTPRESSED;
  glob.displaystate = DISPLAY_EC;
  glob.batcheckcntr = 0;

#ifdef DEBUGUART
	prnUART("START",1);
#endif

  delay_ms(50); // need for ssd1306 init

  //loadSettingsEE();

  ssd1306_init();
  ssd1306_clear_display();
  ssd1306_send_command(SSD1306_DISPLAYON);

  scroll_init(11, 2, waterrunning_bitmap);
  while(1){
    scroll_down(11, 2);
    ssd1306_printBitmapX(0, 0, 11, 2, scrlbuff);
    delay_ms(80);
  }
  


	while(1){
	    uint8_t but = getButtonState();
	    
      // check battery every minute
	    if(glob.batcheckcntr>60){
	    }

	    // check button
	    if(but==BUT_PRESSED){ // button is pressed but not released
	        // enter calibration mode
          if(glob.displaystate==DISPLAY_CALIB) glob.displaystate=DISPLAY_CALIBNUMBLINK; else glob.displaystate=DISPLAY_CALIB;
          ssd1306_clear_display();
          //TODO: long press
          //ssd1306_printBitmap(0,1,57,2,calib_bitmap);
          if(glob.displaystate==DISPLAY_CALIB) ssd1306_printNumber(123);
          delay_ms(250);
      }else if(but==BUT_LONGPRESS){
          // button is released from long press

      }else if(but==BUT_SHORTPRESS){
        // freeze/unfreeze display
      }else{
          // TODO: no button pressed
        if(glob.displaystate!=DISPLAY_EC) ssd1306_clear_display();
        glob.displaystate=DISPLAY_EC;
        //ssd1306_printBitmap(0,1,29,3,ec_bitmap);
        delay_ms(100);
      }
	}

}
